server:
  port: 80
cusproxy:
  port: 9999
  type: GENERAL
  user: utest
  password: upwd
  proxy_type: socks5
  proxy_host: 127.0.0.1
  proxy_port: 7891
cusheart:
  url: http://127.0.0.1:81/api/v1/heart
