server:
  port: 81
spring:
  web:
    resources:
      add-mappings: false
  mvc:
    throw-exception-if-no-handler-found: true
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: java-proxy-manager
      auto-offset-reset: earliest
